const { buildUISchema, buildUISubSchema } = require( './uischema.js' );
const {
	isArrayControl,
	isBooleanControl,
	isIntegerControl,
	isNumberControl,
	isStringControl,
	isEnumControl,
	isSimpleStringArrayControl,
	isMultiSelectEnumControl,
	isObjectControl,
	extractRef,
	rankRenderer,
	rankWith,
	schemaControlIs,
	schemaTypeIs,
} = require( './testers.js' );

module.exports = exports = {
	buildUISchema,
	buildUISubSchema,
	isArrayControl,
	isBooleanControl,
	isIntegerControl,
	isNumberControl,
	isObjectControl,
	isStringControl,
	isEnumControl,
	isSimpleStringArrayControl,
	isMultiSelectEnumControl,
	extractRef,
	rankRenderer,
	rankWith,
	schemaControlIs,
	schemaTypeIs,
};
